name: baidu_face_flutter
description: A new Flutter project.
version: 0.0.1+1
author: y1911214317@qq.com
homepage: www.yilinwuliu.cn

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.fluttify.baidu_face_flutter
        pluginClass: BaiduFaceFlutterPlugin
      ios:
        pluginClass: BaiduFaceFlutterPlugin
